development:
  adapter: postgresql
  database: Ernesto1
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: Ernesto1
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: Ernesto1
  encoding: utf8
  pool: 5
  timeout: 5000
